;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/BidirectionalFreightPlatforms/Content/Localization/BidirectionalFreightPlatforms
DestinationPath=Mods/GameFeatures/BidirectionalFreightPlatforms/Content/Localization/BidirectionalFreightPlatforms
ManifestName=BidirectionalFreightPlatforms.manifest
ArchiveName=BidirectionalFreightPlatforms.archive
CulturesToGenerate=en
CulturesToGenerate=fr
CulturesToGenerate=es
CulturesToGenerate=de

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=BidirectionalFreightPlatforms.csv

