;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/BidirectionalFreightPlatforms/Content/Localization/BidirectionalFreightPlatforms
DestinationPath=Mods/GameFeatures/BidirectionalFreightPlatforms/Content/Localization/BidirectionalFreightPlatforms
ManifestName=BidirectionalFreightPlatforms.manifest
ArchiveName=BidirectionalFreightPlatforms.archive
ResourceName=BidirectionalFreightPlatforms.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
bValidateRichTextTags=false
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=fr
CulturesToGenerate=es
CulturesToGenerate=de

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

